name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Common Functions Library
        working-directory: ./common-functions
        run: |
          lein pom
          lein jar
          lein install

      - name: Build Session Service
        working-directory: ./session-service
        run: lein uberjar

      - name: Build Warranty Service
        working-directory: ./warranty-service
        run: lein uberjar

      - name: Build Warehouse Service
        working-directory: ./warehouse-service
        run: lein uberjar

      - name: Build Order Service
        working-directory: ./order-service
        run: lein uberjar

      - name: Build Store Service
        working-directory: ./store-service
        run: lein uberjar

      - name: Deploy Session Service
        working-directory: ./session-service
        env:
          HEROKU_API_KEY: b74cd257-882f-4f56-ac85-26e14df908b6
          APP_NAME: lab4-xomav2-session-service
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Deploy Warranty Service
        working-directory: ./warranty-service
        env:
          HEROKU_API_KEY: b74cd257-882f-4f56-ac85-26e14df908b6
          APP_NAME: lab2-xomav2-warranty-service
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Deploy Warehouse Service
        working-directory: ./warehouse-service
        env:
          HEROKU_API_KEY: b74cd257-882f-4f56-ac85-26e14df908b6
          APP_NAME: lab2-xomav2-warehouse-service
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Deploy Order Service
        working-directory: ./order-service
        env:
          HEROKU_API_KEY: b74cd257-882f-4f56-ac85-26e14df908b6
          APP_NAME: lab2-xomav2-order-service
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Deploy Store Service
        working-directory: ./store-service
        env:
          HEROKU_API_KEY: b74cd257-882f-4f56-ac85-26e14df908b6
          APP_NAME: lab2-xomav2-store-service
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
